### ISSUE TITLE
Please release master as a new version to Ansible Galaxy

### ISSUE THREAD

**Issue by ghost** [robertdebock/ansible-role-rpmfusion#1]
Hello Robert,

could you please release the current `master` as a new version to Ansible Galaxy? The current version does not work with Fedora 33, which was released a few days ago.

Best regards and thanks for writing and keeping the playbook up to date!

**Comment by robertdebock** [comment]
You are right, just ran into this issue as well.

It's been released. Thanks @markus289 for the reminder.
